name: hamal

on:
#  schedule:
#    - cron:  '0,30 * * * *'
  push:
    branches:
      - develop

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t the-daily-show-with-trevor-noah .
      - name: Run
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          retry_wait_seconds: 300
          max_attempts: 3
          retry_on: any
          command: docker run --name han the-daily-show-with-trevor-noah && mkdir download && docker cp han:/app download
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: download

