name: hamal

on:
#  schedule:
#    - cron:  '0,30 * * * *'
  push:
    branches:
      - develop

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t the-daily-show .
      - name: Run
        run: docker run --name han the-daily-show && mkdir download && docker cp han:/app download
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: download

